<a href="https://colab.research.google.com/github/alisterpage/CHEM3580-Jupyter-Notebooks/blob/main/twisting_carbenes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!pip install pyscf pyberny py3Dmol fortecubeview pythreejs -q 2>&1 >/dev/null

In [25]:
import pyscf
from pyscf import gto, scf, tools, lo, lib
from pyscf.geomopt.berny_solver import optimize
import py3Dmol
import fortecubeview
from google.colab import output
output.enable_custom_widget_manager()
import numpy as np
#from __future__ import print_function
#import sys
#log = lib.logger.Logger(sys.stdout, 0)
#log.verbose = 0


In [26]:
mol = gto.Mole()
mol.atom = '''
    C
    H 1 1.1
    H 1 1.1 2 109.5
    H 1 1.1 2 109.5 3 120
'''
mol.basis = '6-31g(d)'
mol.spin=1;
mol.build();
mf = scf.RHF(mol)
mf.xc = 'b3lyp'

# Optimize the geometry
mol_eq = optimize(mf, maxsteps=100)
#print(mol_eq.atom_coords())

# Get the optimized energy
mf = scf.RHF(mol)
mf.xc = 'b3lyp'
mf.scf()


INFO:pyscf.geomopt.berny_solver.139863245647936:0 Internal coordinates:
INFO:pyscf.geomopt.berny_solver.139863245647936:0 * Number of fragments: 1
INFO:pyscf.geomopt.berny_solver.139863245647936:0 * Number of internal coordinates: 6
INFO:pyscf.geomopt.berny_solver.139863245647936:0 * Number of strong bonds: 3
INFO:pyscf.geomopt.berny_solver.139863245647936:0 * Number of strong angles: 3



Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   1.100000   0.000000   0.000000    0.000000  0.000000  0.000000
   H  -0.367188   0.000000   1.036906    0.000000  0.000000  0.000000
   H  -0.367188   0.897987  -0.518453    0.000000  0.000000  0.000000
converged SCF energy = -39.5454868007801
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 C    -0.0175293204    -0.0431944078    -0.0249383030
1 H     0.0130335764     0.0121859067     0.0070355365
2 H     0.0022478720     0.0122429619     0.0146001008
3 H     0.0022478720     0.0187655392     0.0033026656
----------------------------------------------
cycle 1: E = -39.5454868008  dE = -39.5455  norm(grad) = 0.0624422


INFO:pyscf.geomopt.berny_solver.139863245647936:1 Energy: -39.5454868008
INFO:pyscf.geomopt.berny_solver.139863245647936:1 Pure RFO step was performed:
INFO:pyscf.geomopt.berny_solver.139863245647936:1 * Trust radius: 0.3
INFO:pyscf.geomopt.berny_solver.139863245647936:1 * Number of negative eigenvalues: 0
INFO:pyscf.geomopt.berny_solver.139863245647936:1 * Lowest eigenvalue: 0.164
INFO:pyscf.geomopt.berny_solver.139863245647936:1 * lambda: -0.0154
INFO:pyscf.geomopt.berny_solver.139863245647936:1 Quadratic step: RMS: 0.117, max: 0.164
INFO:pyscf.geomopt.berny_solver.139863245647936:1 * Predicted energy change: -0.00835
INFO:pyscf.geomopt.berny_solver.139863245647936:1 Total step: RMS: 0.117, max: 0.164
INFO:pyscf.geomopt.berny_solver.139863245647936:1 Perfect transformation to cartesians in 19 iterations
INFO:pyscf.geomopt.berny_solver.139863245647936:1 * RMS(dcart): 9.2e-07, RMS(dq): 1.13e-06
INFO:pyscf.geomopt.berny_solver.139863245647936:1 Convergence criteria:
INFO:pyscf.geomopt.b


Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.062224   0.152884   0.088268    0.062224  0.152884  0.088268
   H   1.118982  -0.063113  -0.036438    0.018982 -0.063113 -0.036438
   H  -0.407791  -0.063314   1.042909   -0.040603 -0.063314  0.006004
   H  -0.407791   0.871529  -0.576286   -0.040603 -0.026458 -0.057833

WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.

converged SCF energy = -39.5541244263193
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 C    -0.0011389066    -0.0028716497    -0.0016579477
1 H     0.0096969994    -0.0018960245    -0.0010946702
2 H    -0.0042790464    -0.0018941239     0.0087859548
3 H    -0.0042790464     0.0066617981    -0.0060333368
----------------------------------------------
cycle 2: E = -39.5541244263  dE = -0.00863763 

INFO:pyscf.geomopt.berny_solver.139863245647936:2 Energy: -39.5541244263
INFO:pyscf.geomopt.berny_solver.139863245647936:2 Hessian update information:
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Change: RMS: 0.014, max: 0.0178
INFO:pyscf.geomopt.berny_solver.139863245647936:2 Trust update: Fletcher's parameter: 1.03
INFO:pyscf.geomopt.berny_solver.139863245647936:2 Linear interpolation:
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Energies: -39.554124, -39.545487
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Derivatives: 0.00107, 0.0154
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Quartic interpolation was performed: t = -0.0632
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Interpolated energy: -39.554158
INFO:pyscf.geomopt.berny_solver.139863245647936:2 Pure RFO step was performed:
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Trust radius: 0.3
INFO:pyscf.geomopt.berny_solver.139863245647936:2 * Number of negative eigenvalues: 0
INFO:pyscf.geomo


Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.070871   0.174156   0.100549    0.008648  0.021272  0.012282
   H   1.107148  -0.067463  -0.038950   -0.011834 -0.004350 -0.002512
   H  -0.406197  -0.067690   1.030948    0.001593 -0.004376 -0.011961
   H  -0.406197   0.858983  -0.574095    0.001593 -0.012547  0.002191

WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.

converged SCF energy = -39.5545238996272
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 C    -0.0000237716    -0.0000774354    -0.0000447074
1 H     0.0009803684    -0.0002721193    -0.0001571082
2 H    -0.0004782984    -0.0002731278     0.0008767024
3 H    -0.0004782984     0.0006226826    -0.0006748868
----------------------------------------------
cycle 3: E = -39.5545238996  dE = -0.000399473

INFO:pyscf.geomopt.berny_solver.139863245647936:3 Energy: -39.5545238996
INFO:pyscf.geomopt.berny_solver.139863245647936:3 Hessian update information:
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Change: RMS: 0.00882, max: 0.0163
INFO:pyscf.geomopt.berny_solver.139863245647936:3 Trust update: Fletcher's parameter: 1.23
INFO:pyscf.geomopt.berny_solver.139863245647936:3 Linear interpolation:
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Energies: -39.554524, -39.554124
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Derivatives: 6.29e-05, 0.000728
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Quartic interpolation was performed: t = -0.091
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Interpolated energy: -39.554527
INFO:pyscf.geomopt.berny_solver.139863245647936:3 Pure RFO step was performed:
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Trust radius: 0.3
INFO:pyscf.geomopt.berny_solver.139863245647936:3 * Number of negative eigenvalues: 0
INFO:pyscf.g


Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.069438   0.170654   0.098527   -0.001434 -0.003502 -0.002022
   H   1.105943  -0.065780  -0.037978   -0.001205  0.001683  0.000971
   H  -0.404878  -0.066008   1.030137    0.001319  0.001682 -0.000812
   H  -0.404878   0.859120  -0.572233    0.001319  0.000138  0.001862
converged SCF energy = -39.5545280627596
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 C    -0.0000068480    -0.0000189449    -0.0000109378
1 H    -0.0000761899     0.0000302870     0.0000174862
2 H     0.0000415189     0.0000301732    -0.0000653582
3 H     0.0000415189    -0.0000415153     0.0000588099
----------------------------------------------
cycle 4: E = -39.5545280628  dE = -4.16313e-06  norm(grad) = 0.000146169


INFO:pyscf.geomopt.berny_solver.139863245647936:4 Energy: -39.5545280628
INFO:pyscf.geomopt.berny_solver.139863245647936:4 Hessian update information:
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Change: RMS: 0.00812, max: 0.00975
INFO:pyscf.geomopt.berny_solver.139863245647936:4 Trust update: Fletcher's parameter: 2.39
INFO:pyscf.geomopt.berny_solver.139863245647936:4 Linear interpolation:
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Energies: -39.554528, -39.554524
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Derivatives: -1.08e-06, 9.41e-06
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Quartic interpolation was performed: t = 0.103
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Interpolated energy: -39.554528
INFO:pyscf.geomopt.berny_solver.139863245647936:4 Pure RFO step was performed:
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Trust radius: 0.3
INFO:pyscf.geomopt.berny_solver.139863245647936:4 * Number of negative eigenvalues: 0
INFO:pyscf.

converged SCF energy = -39.5454868007802


-39.545486800780175

In [35]:
def compute_dihedral_angle(a, b, c, d):
    # Compute the vectors between the atoms
    ab = np.subtract(b,a)
    bc = np.subtract(c,b)
    cd = np.subtract(d,c)
    
    # Compute the normal vectors to the planes formed by the vectors
    n1 = np.cross(ab, bc)
    n2 = np.cross(bc, cd)
    
    # Compute the dihedral angle using the dot product and cross product
    dihedral_angle = np.arctan2(np.dot(n1, cd), np.dot(n1, n2)) * 180 / np.pi
    
    return dihedral_angle

# Define the atomic coordinates
xyz = mol.atom_coords()
c = np.array([xyz[0][1], xyz[0][2], xyz[0][2]])
h1 = np.array([xyz[1][1], xyz[1][2], xyz[1][2]])
h2 = np.array([xyz[2][1], xyz[2][2], xyz[2][2]])
h3 = np.array([xyz[3][1], xyz[3][2], xyz[3][2]])

# Compute the dihedral angle
dihedral_angle = compute_dihedral_angle(h1,h2,h3,c)

# Print the dihedral angle
print("Dihedral angle:", dihedral_angle,"deg.\n")

print('Final Energy:', mf.e_tot,"Hartree\n")
print('Final coordinates (Angstroms)\n',mol_eq.atom_coords())

Dihedral angle: 0.0 deg.

Final Energy: -39.545486800780175 Hartree

Final coordinates (Angstroms)
 [[ 0.13121854  0.32249009  0.18618974]
 [ 2.08992957 -0.12430654 -0.07176841]
 [-0.76510858 -0.12473705  1.94667593]
 [-0.76510858  1.62350229 -1.08136342]]


In [31]:
def get_mo(mf, mol):
    """Get molecular orbitals"""
    orbitals = {"canonical": mf.mo_coeff}

    # Get intrinsic bonding orbitals and localized intrinsic valence virtual orbitals (livvo):
    orbocc = mf.mo_coeff[:, 0 : mol.nelec[0]]
    orbvirt = mf.mo_coeff[:, mol.nelec[0] :]

    ovlpS = mol.intor_symmetric("int1e_ovlp")

    iaos = lo.iao.iao(mol, orbocc)
    iaos = lo.orth.vec_lowdin(iaos, ovlpS)
    ibos = lo.ibo.ibo(mol, orbocc, locmethod="IBO")
    orbitals["ibo"] = ibos

    livvo = lo.vvo.livvo(mol, orbocc, orbvirt)
    orbitals["livvo"] = livvo
    return orbitals

orbitals = get_mo(mf, mol_eq);

 Iterative localization: IB/P4/2x2, 6 iter; Final gradient 9.74e-10
 Iterative localization: IB/P4/2x2, 8 iter; Final gradient 7.14e-10


In [32]:
def find_homo_lumo(mf):
    lumo = float("inf")
    lumo_idx = None
    homo = -float("inf")
    homo_idx = None
    for i, (energy, occ) in enumerate(zip(mf.mo_energy, mf.mo_occ)):
        if occ > 0 and energy > homo:
            homo = energy
            homo_idx = i
        if occ == 0 and energy < lumo:
            lumo = energy
            lumo_idx = i

    return homo, homo_idx, lumo, lumo_idx

_, homo_idx, _, lumo_idx = find_homo_lumo(mf)

In [33]:
tools.cubegen.orbital(
    mol, "opt.cube", orbitals["canonical"][:, homo_idx], margin=5,nx=10,ny=10,nz=10
);

In [34]:

data = None
with open("opt.cube", "r") as infile:
    data = infile.read()
view = py3Dmol.view()
view.addVolumetricData(
    data,
    "cube",
    {
        "isoval": 1.0,
        "volformat": "cube",
    },
)
view.addModel(data, "cube")
view.setStyle({"stick": {}})
view.zoomTo()
view.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol